### ISSUE TITLE
Consider using NoSuspend for sleep inhibition

### ISSUE THREAD

**Issue by KOLANICH** [GalliumOS/update-manager#1]
https://github.com/KOLANICH/NoSuspend.py

**Comment by coltondrg** [comment]
Why? Are you saying suspend should be inhibited _during_ the update process?

**Comment by KOLANICH** [comment]
In fact it is already done in this software for the purpose you have said.

https://github.com/GalliumOS/update-manager/blob/b75e0bb20205a9eaba4d7cc6f04a50819799c554/UpdateManager/Core/utils.py#L354L376
https://github.com/GalliumOS/update-manager/blob/b75e0bb20205a9eaba4d7cc6f04a50819799c554/UpdateManager/backend/__init__.py#L30

I just developed a quite portable library (works both for Windows and should work for several desktop environments for Linux, MacOS is not implemented yet because I don't have it and don't use it, but feel free to make a PR).

**Comment by coltondrg** [comment]
If it ain't broke, don't fix it. I'll keep that in mind next time I need something to do that, however. Thank you.
